### ISSUE TITLE
Cannot open include file: 'ModuleManager.h'

### ISSUE THREAD

**Issue by goldngood** [getnamo/BLUI#36]
I am trying to build the plugin on AngelScript-UE (An version of UnrealEngine that comes with AngelScript) and i get this :
`/Documents/Unreal Projects/NARCO_/Plugins/BLUI/Source/BluLoader/Private/BluLoaderPrivatePCH.h(6): fatal error C1083: Cannot open include file: 'ModuleManager.h': No such file or directory`

Does anyone have any idea?

**Comment by goldngood** [comment]
I fixed the problem it seems that i needed to use `#include "Modules/ModuleManager.h"`

**Comment by malcriado3d** [comment]
im still getting this error:
Severity Code Description Project File Line Suppression State
Error C1083 Cannot open include file: 'WindowsHWrapper.h': No such file or directory PROJECT\Plugins\BLUI\Source\Blu\Public\BluManager.h 4

**Comment by getnamo** [comment]
Prepend ```Windows/``` before that header
